import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <Navbar />
          <main className="flex-grow"> {children}</main>
          <footer id="contact" className="bg-gray-800 py-6">
            <div className="container mx-auto px-4 text-center text-white">
              <p className="mb-4">
                &copy; {new Date().getFullYear()} Inventory System. All rights
                reserved.
              </p>
              <p>Contact us: info@inventorysystem.com</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
